import type { Patient, Session, Payment, CalendarEvent } from './types';

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'p1',
    name: 'Ana Clara Souza',
    email: 'anaclara@email.com',
    phone: '(11) 99234-5678',
    birthDate: '1990-03-15',
    gender: 'F',
    status: 'ativo',
    sessionValue: 180,
    paymentMethod: 'pix',
    paymentDueDay: 10,
    chiefComplaint: 'Ansiedade generalizada e dificuldades nos relacionamentos interpessoais.',
    medicalHistory: 'Histórico de ansiedade desde a adolescência. Fez terapia por 2 anos aos 22 anos. Sem internações.',
    medications: 'Sertralina 50mg (prescrita pelo psiquiatra Dr. Carlos)',
    createdAt: '2024-02-10',
    nextSession: '2026-05-26T10:00',
    totalSessions: 24,
    pendingPayment: 0,
  },
  {
    id: 'p2',
    name: 'Bruno Mendes',
    email: 'brunomendes@email.com',
    phone: '(21) 98765-4321',
    birthDate: '1985-07-22',
    gender: 'M',
    status: 'ativo',
    sessionValue: 200,
    paymentMethod: 'cartão',
    paymentDueDay: 5,
    chiefComplaint: 'Depressão moderada após separação. Dificuldade de adaptação e insônia.',
    medicalHistory: 'Separação conjugal em jan/2025. Episódio depressivo leve em 2019. Pai faleceu em 2023.',
    medications: 'Sem medicação atual',
    createdAt: '2025-01-15',
    nextSession: '2026-05-27T14:00',
    totalSessions: 16,
    pendingPayment: 200,
  },
  {
    id: 'p3',
    name: 'Carla Ferreira',
    email: 'carlafer@email.com',
    phone: '(31) 97654-3210',
    birthDate: '1998-11-08',
    gender: 'F',
    status: 'novo',
    sessionValue: 150,
    paymentMethod: 'pix',
    paymentDueDay: 15,
    chiefComplaint: 'Dificuldades de foco e procrastinação. Suspeita de TDAH não diagnosticado.',
    medicalHistory: 'Diagnóstico de TDAH em avaliação. Histórico familiar de transtornos de atenção.',
    medications: 'Nenhuma',
    createdAt: '2026-05-01',
    nextSession: '2026-05-28T09:00',
    totalSessions: 2,
    pendingPayment: 0,
  },
  {
    id: 'p4',
    name: 'Diego Alves',
    email: 'diegoalves@email.com',
    phone: '(11) 94567-8901',
    birthDate: '1979-06-03',
    gender: 'M',
    status: 'ativo',
    sessionValue: 220,
    paymentMethod: 'pix',
    paymentDueDay: 20,
    chiefComplaint: 'Síndrome de burnout e conflitos no ambiente corporativo. Dificuldade em estabelecer limites.',
    medicalHistory: 'Executivo de alta performance. Dois episódios de burnout (2018 e 2024). Hipertensão controlada.',
    medications: 'Losartana 50mg, Clonazepam 0,5mg conforme necessidade',
    createdAt: '2025-08-12',
    nextSession: '2026-05-26T16:00',
    totalSessions: 32,
    pendingPayment: 0,
  },
  {
    id: 'p5',
    name: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    phone: '(19) 99876-5432',
    birthDate: '2002-01-20',
    gender: 'F',
    status: 'ativo',
    sessionValue: 160,
    paymentMethod: 'pix',
    paymentDueDay: 25,
    chiefComplaint: 'Transtorno alimentar em remissão. Distorção de imagem corporal e baixa autoestima.',
    medicalHistory: 'Anorexia nervosa diagnosticada aos 19 anos. Em acompanhamento nutricional concomitante. Família participativa no tratamento.',
    medications: 'Fluoxetina 20mg',
    createdAt: '2025-03-05',
    nextSession: '2026-05-29T11:00',
    totalSessions: 44,
    pendingPayment: 0,
  },
  {
    id: 'p6',
    name: 'Rafael Costa',
    email: 'rafacosta@email.com',
    phone: '(85) 98123-4567',
    birthDate: '1993-09-14',
    gender: 'M',
    status: 'inativo',
    sessionValue: 170,
    paymentMethod: 'cartão',
    paymentDueDay: 10,
    chiefComplaint: 'Fobia social e timidez extrema. Evitação de situações públicas.',
    medicalHistory: 'Fobia social desde a adolescência. Último episódio de crise de pânico em março/2026. Interrompeu o tratamento por mudança de cidade.',
    medications: 'Escitalopram 10mg',
    createdAt: '2024-09-20',
    nextSession: '',
    totalSessions: 18,
    pendingPayment: 170,
  },
];

export const MOCK_SESSIONS: Session[] = [
  // Ana Clara (p1) - 24 sessões registradas, últimas 8
  { id: 's1', patientId: 'p1', date: '2026-05-19', time: '10:00', duration: 50, status: 'realizada', notes: 'Paciente relatou melhora significativa na qualidade do sono. Trabalhamos técnicas de respiração para momentos de crise. Ativação comportamental em progresso.', charged: true, value: 180 },
  { id: 's2', patientId: 'p1', date: '2026-05-12', time: '10:00', duration: 50, status: 'realizada', notes: 'Foco em identificação de gatilhos ansiosos no ambiente de trabalho. Tarefa: diário de pensamentos automáticos.', charged: true, value: 180 },
  { id: 's3', patientId: 'p1', date: '2026-05-05', time: '10:00', duration: 50, status: 'cancelada', notes: 'Cancelada pela paciente: compromisso profissional inadiável.', charged: false, value: 0 },
  { id: 's3b', patientId: 'p1', date: '2026-04-28', time: '10:00', duration: 50, status: 'realizada', notes: 'Revisão dos pensamentos disfuncionais identificados. Progresso na assertividade com a chefe.', charged: true, value: 180 },
  { id: 's3c', patientId: 'p1', date: '2026-04-21', time: '10:00', duration: 50, status: 'realizada', notes: 'Abordagem de esquemas precoces. Discussão sobre padrão de autossacrifício.', charged: true, value: 180 },
  // Bruno (p2)
  { id: 's4', patientId: 'p2', date: '2026-05-20', time: '14:00', duration: 60, status: 'realizada', notes: 'Bruno demonstrou avanço no processo de aceitação. Iniciamos trabalho de reestruturação de rotinas pós-separação. Discussão sobre novos projetos de vida.', charged: false, value: 200 },
  { id: 's5', patientId: 'p2', date: '2026-05-13', time: '14:00', duration: 60, status: 'realizada', notes: 'Sessão intensa sobre luto pelo casamento. Técnica de EMDR iniciada para processar memórias dolorosas.', charged: true, value: 200 },
  { id: 's5b', patientId: 'p2', date: '2026-05-06', time: '14:00', duration: 60, status: 'faltou', notes: 'Não compareceu e não avisou previamente. Contato por WhatsApp realizado no dia seguinte.', charged: false, value: 0 },
  { id: 's5c', patientId: 'p2', date: '2026-04-29', time: '14:00', duration: 60, status: 'realizada', notes: 'Exploração do papel de pai. Preocupação com os filhos durante a transição pós-divórcio.', charged: true, value: 200 },
  // Carla (p3)
  { id: 's6', patientId: 'p3', date: '2026-05-14', time: '09:00', duration: 50, status: 'realizada', notes: 'Segunda sessão. Aprofundamento das queixas de desatenção. Aplicação de questionário Conners para triagem de TDAH.', charged: true, value: 150 },
  { id: 's7', patientId: 'p3', date: '2026-05-07', time: '09:00', duration: 50, status: 'realizada', notes: 'Sessão de anamnese completa. Histórico acadêmico, familiar e profissional levantados.', charged: true, value: 150 },
  // Diego (p4)
  { id: 's8', patientId: 'p4', date: '2026-05-19', time: '16:00', duration: 60, status: 'realizada', notes: 'Discussão sobre limites no ambiente de trabalho. Diego conseguiu dizer "não" para dois projetos extras essa semana — grande avanço.', charged: true, value: 220 },
  { id: 's9', patientId: 'p4', date: '2026-05-12', time: '16:00', duration: 60, status: 'realizada', notes: 'Revisão do planejamento de férias. Abordagem sobre síndrome do impostor e perfeccionismo como mecanismo de defesa.', charged: true, value: 220 },
  { id: 's9b', patientId: 'p4', date: '2026-05-05', time: '16:00', duration: 60, status: 'realizada', notes: 'Técnica de regulação emocional aplicada para situações de conflito com pares na empresa.', charged: true, value: 220 },
  // Fernanda (p5)
  { id: 's10', patientId: 'p5', date: '2026-05-21', time: '11:00', duration: 50, status: 'realizada', notes: 'Fernanda relatou semana positiva com alimentação. Autocompaixão em desenvolvimento. Trabalho com espelho realizado sem grande resistência.', charged: true, value: 160 },
  { id: 's11', patientId: 'p5', date: '2026-05-14', time: '11:00', duration: 50, status: 'realizada', notes: 'Sessão focada em reestruturação cognitiva sobre padrões de beleza. Leitura indicada: The Body Is Not An Apology.', charged: true, value: 160 },
  { id: 's11b', patientId: 'p5', date: '2026-05-07', time: '11:00', duration: 50, status: 'realizada', notes: 'Discussão sobre relacionamento com a mãe e pressões estéticas familiares.', charged: true, value: 160 },
  // Rafael (p6) - inativo
  { id: 's12', patientId: 'p6', date: '2026-03-10', time: '15:00', duration: 50, status: 'realizada', notes: 'Última sessão antes da mudança. Encaminhamento para profissional em Fortaleza. Resumo do processo terapêutico entregue.', charged: true, value: 170 },
  { id: 's13', patientId: 'p6', date: '2026-03-03', time: '15:00', duration: 50, status: 'realizada', notes: 'Penúltima sessão. Trabalho de exposição gradual a situações sociais — restaurante e metrô nos horários de pico.', charged: false, value: 170 },
];

export const MOCK_PAYMENTS: Payment[] = [
  { id: 'pay1', patientId: 'p1', sessionId: 's1', date: '2026-05-19', amount: 180, status: 'pago', method: 'pix', description: 'Sessão 19/05' },
  { id: 'pay2', patientId: 'p1', sessionId: 's2', date: '2026-05-12', amount: 180, status: 'pago', method: 'pix', description: 'Sessão 12/05' },
  { id: 'pay2b', patientId: 'p1', sessionId: 's3b', date: '2026-04-28', amount: 180, status: 'pago', method: 'pix', description: 'Sessão 28/04' },
  { id: 'pay2c', patientId: 'p1', sessionId: 's3c', date: '2026-04-21', amount: 180, status: 'pago', method: 'pix', description: 'Sessão 21/04' },
  { id: 'pay3', patientId: 'p2', sessionId: 's4', date: '2026-05-20', amount: 200, status: 'pendente', method: 'cartão', description: 'Sessão 20/05' },
  { id: 'pay4', patientId: 'p2', sessionId: 's5', date: '2026-05-13', amount: 200, status: 'pago', method: 'cartão', description: 'Sessão 13/05' },
  { id: 'pay4b', patientId: 'p2', sessionId: 's5c', date: '2026-04-29', amount: 200, status: 'pago', method: 'cartão', description: 'Sessão 29/04' },
  { id: 'pay5', patientId: 'p3', sessionId: 's6', date: '2026-05-14', amount: 150, status: 'pago', method: 'pix', description: 'Sessão 14/05' },
  { id: 'pay6', patientId: 'p3', sessionId: 's7', date: '2026-05-07', amount: 150, status: 'pago', method: 'pix', description: 'Sessão 07/05' },
  { id: 'pay7', patientId: 'p4', sessionId: 's8', date: '2026-05-19', amount: 220, status: 'pago', method: 'pix', description: 'Sessão 19/05' },
  { id: 'pay8', patientId: 'p4', sessionId: 's9', date: '2026-05-12', amount: 220, status: 'pago', method: 'pix', description: 'Sessão 12/05' },
  { id: 'pay8b', patientId: 'p4', sessionId: 's9b', date: '2026-05-05', amount: 220, status: 'pago', method: 'pix', description: 'Sessão 05/05' },
  { id: 'pay9', patientId: 'p5', sessionId: 's10', date: '2026-05-21', amount: 160, status: 'pago', method: 'pix', description: 'Sessão 21/05' },
  { id: 'pay10', patientId: 'p5', sessionId: 's11', date: '2026-05-14', amount: 160, status: 'pago', method: 'pix', description: 'Sessão 14/05' },
  { id: 'pay10b', patientId: 'p5', sessionId: 's11b', date: '2026-05-07', amount: 160, status: 'pago', method: 'pix', description: 'Sessão 07/05' },
  { id: 'pay11', patientId: 'p6', sessionId: 's12', date: '2026-03-10', amount: 170, status: 'pago', method: 'cartão', description: 'Sessão 10/03' },
  { id: 'pay12', patientId: 'p6', sessionId: 's13', date: '2026-03-03', amount: 170, status: 'atrasado', method: 'cartão', description: 'Sessão 03/03 — não pago' },
];

export const MOCK_CALENDAR: CalendarEvent[] = [
  // Passado — semana de 19/05
  { id: 'c6', patientId: 'p1', patientName: 'Ana Clara Souza', date: '2026-05-19', time: '10:00', duration: 50, status: 'realizada', recurrence: 'semanal' },
  { id: 'c7', patientId: 'p2', patientName: 'Bruno Mendes', date: '2026-05-20', time: '14:00', duration: 60, status: 'realizada', recurrence: 'semanal' },
  { id: 'c8', patientId: 'p5', patientName: 'Fernanda Lima', date: '2026-05-21', time: '11:00', duration: 50, status: 'realizada', recurrence: 'semanal' },
  { id: 'c9', patientId: 'p4', patientName: 'Diego Alves', date: '2026-05-19', time: '16:00', duration: 60, status: 'realizada', recurrence: 'semanal' },
  // Esta semana — 26-30/05
  { id: 'c1', patientId: 'p1', patientName: 'Ana Clara Souza', date: '2026-05-26', time: '10:00', duration: 50, status: 'agendada', recurrence: 'semanal' },
  { id: 'c10', patientId: 'p4', patientName: 'Diego Alves', date: '2026-05-26', time: '16:00', duration: 60, status: 'agendada', recurrence: 'semanal' },
  { id: 'c2', patientId: 'p2', patientName: 'Bruno Mendes', date: '2026-05-27', time: '14:00', duration: 60, status: 'agendada', recurrence: 'semanal' },
  { id: 'c3', patientId: 'p3', patientName: 'Carla Ferreira', date: '2026-05-28', time: '09:00', duration: 50, status: 'agendada', recurrence: 'quinzenal' },
  { id: 'c11', patientId: 'p5', patientName: 'Fernanda Lima', date: '2026-05-29', time: '11:00', duration: 50, status: 'agendada', recurrence: 'semanal' },
  // Próxima semana — 02-06/06
  { id: 'c4', patientId: 'p1', patientName: 'Ana Clara Souza', date: '2026-06-02', time: '10:00', duration: 50, status: 'agendada', recurrence: 'semanal' },
  { id: 'c12', patientId: 'p4', patientName: 'Diego Alves', date: '2026-06-02', time: '16:00', duration: 60, status: 'agendada', recurrence: 'semanal' },
  { id: 'c5', patientId: 'p2', patientName: 'Bruno Mendes', date: '2026-06-03', time: '14:00', duration: 60, status: 'agendada', recurrence: 'semanal' },
  { id: 'c13', patientId: 'p5', patientName: 'Fernanda Lima', date: '2026-06-05', time: '11:00', duration: 50, status: 'agendada', recurrence: 'semanal' },
];

export const WEEKLY_REVENUE = [
  { week: 'Sem 1', value: 660 },
  { week: 'Sem 2', value: 1090 },
  { week: 'Sem 3', value: 910 },
  { week: 'Sem 4', value: 1380 },
];

// Dados de receita mensal para gráficos de tendência
export const MONTHLY_REVENUE = [
  { month: 'Jan', value: 2800 },
  { month: 'Fev', value: 3200 },
  { month: 'Mar', value: 2900 },
  { month: 'Abr', value: 3800 },
  { month: 'Mai', value: 4040 },
];
